services:
  database:
    image: mariadb
    restart: always
    volumes:
        - ./volumes/mysql_data:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: root
  ytdownloader.api:
    image: ${DOCKER_REGISTRY-}ytdownloaderapi
    depends_on:
        - database
    environment:
        - DATABASE_NAME=ytDownload
        - DATABASE_USER=root
        - DATABASE_PASSWORD=root
        - DATABASE_HOST=database
    volumes:
        - ./volumes/youtube:/tmp/youtube
        - ./volumes/youtube_later:/tmp/youtube_later
        - ./volumes/finished:/tmp/finished
    ports:
        - 8080:8080
        - 8081:8081
    build:
      context: .
      dockerfile: ./YtDownloader.Api/Dockerfile
