services:
  # database:
  #   image: mariadb
  #   restart: always
  #   volumes:
  #       - ./volumes/mysql_data:/var/lib/mysql
  #   environment:
  #     MARIADB_ROOT_PASSWORD: root
  database:
    image: postgres
    restart: always
    volumes:
      - ./volumes/postgres_data:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: ytDownload
  ytdownloader.api:
    image: ${DOCKER_REGISTRY-}ytdownloaderapi
    depends_on:
        - database
    environment:
        - DATABASE_NAME=ytDownload
        - DATABASE_USER=root
        - DATABASE_PASSWORD=root
        - DATABASE_HOST=database
    volumes:
        - ./volumes/youtube:/tmp/youtube
        - ./volumes/youtube_later:/tmp/youtube_later
        - ./volumes/finished:/tmp/finished
        - ./volumes/cookies:/tmp/cookies  
    ports:
        - 8080:8080
        - 8081:8081
    build:
      context: .
      dockerfile: ./YtDownloader.Api/Dockerfile
