name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image with Git SHA
      run: |
        set -e
        docker build --pull --no-cache \
          --file Dockerfile \
          --cache-from=type=gha \
          --cache-to=type=gha,mode=max \
          --label "org.opencontainers.image.revision=${{ github.sha }}" \
          --label "org.opencontainers.image.created=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" \
          --label "org.opencontainers.image.source=${{ github.repository }}" \
          --tag ${{ secrets.DOCKER_USERNAME }}/ytdownloader:${{ github.sha }} \
          .

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/ytdownloader:${{ github.sha }}

    - name: Push Docker image with latest tag
      if: github.ref == 'refs/heads/master'
      run: |
        set -e
        docker tag ${{ secrets.DOCKER_USERNAME }}/ytdownloader:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/ytdownloader:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/ytdownloader:latest
